# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0007_auto_20170929_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='logreg.Users'),
        ),
    ]
