# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0013_auto_20171002_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels',
            name='creator',
        ),
    ]
